
services:
  yamcs:
    image: takeme2space/mcc:latest
    hostname: mcc
    container_name: mcc
    env_file:
      - .env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${YAMCS_PORT:-8090}/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    ports:
      - "${YAMCS_PORT:-8090}:${YAMCS_PORT:-8090}"
      - "${OBC_TM_PORT:-10015}:${OBC_TM_PORT:-10015}/udp"
    volumes:
      # Persistent data storage
      - yamcs-data:/yamcs/yamcs-data
      # Logs storage
      - yamcs-logs:/yamcs/logs
      # Cache directory
      - yamcs-cache:/yamcs/cache
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - yamcs-network
    restart: unless-stopped
    read_only: false
    deploy:
      resources:
        limits:
          memory: ${MEMORY_LIMIT:-2.5G}
          cpus: '${CPU_LIMIT:-2}'
        reservations:
          memory: ${MEMORY_RESERVATION:-1G}
          cpus: '${CPU_RESERVATION:-0.5}'
    logging:
      driver: "json-file"
      options:
        max-size: "${LOG_MAX_SIZE:-10m}"
        max-file: "${LOG_MAX_FILES:-3}"

  # Optional: Add monitoring with Prometheus
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - prometheus-data:/prometheus
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/usr/share/prometheus/console_libraries'
      - '--web.console.templates=/usr/share/prometheus/consoles'
      - '--web.enable-lifecycle'
    networks:
      - yamcs-network
    restart: unless-stopped
    profiles:
      - monitoring
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'

volumes:
  yamcs-data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${YAMCS_DATA_PATH:-./data/yamcs-data}
  yamcs-logs:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${YAMCS_LOGS_PATH:-./data/yamcs-logs}
  yamcs-cache:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: ${YAMCS_CACHE_PATH:-./data/yamcs-cache}
  prometheus-data:
    driver: local

networks:
  yamcs-network:
    driver: bridge
    ipam:
      config:
        - subnet: ${YAMCS_NETWORK_SUBNET:-172.30.0.0/16}
